default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>_dev

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>_test
